### ISSUE TITLE
Xamarin.Forms 4.5 breaks some controls look and feel

### ISSUE THREAD

**Issue by brcinho** [contrix09/XF-Material-Library#297]
## 🐛 Bug Report
iOS
Material card has darker shadows, slider and switch have additional dot at the beginning.

### Expected behavior

Don't know what is expected to be honest. Is it just bug in Xamarin.Forms 4.5 or this library needs to take some breaking changes in Xamarin.Forms into consideration

### Reproduction steps

It should be easily reproducible.

### Configuration

**Version:** 1.5.x

**Platform:** 
- iphone: iOS -> Yes
- didn't check other platforms

**Comment by AnthonyLatty** [comment]
Yes , i just updated and encounter this on iOS. I ran the same project on Android and it worked as expected so this bug is definitely on iOS only. Most of the controls have darker shadows and missing activity indicators.

**Comment by martijn00** [comment]
@davidortinau do you know if this has been a breaking change in Forms?

**Comment by davidortinau** [comment]
This isn’t something we are aware of. If you think it’s an issue in Xamarin.Forms, please open an issue with a repro over there.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NPadrutt** [comment]
I have the same thing with an app of mine. Additionally my context menu on looks very strange. As well only on iOS

![IMG_0208](https://user-images.githubusercontent.com/1764367/76535403-1720c500-647b-11ea-90f4-1db2fefe771c.PNG)

**Comment by rogerwcpt** [comment]
I have the same issue reported by @NPadrutt 

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13134927/76556104-975a2100-64a1-11ea-919f-e467559782dd.png">

**Comment by brcinho** [comment]
I see that this has potentially been addressed? Any info on the release date and version?

**Comment by rogerwcpt** [comment]
> I see that this has potentially been addressed? Any info on the release date and version?

Also waiting for the fix to be published to Nuget.

**Comment by martijn00** [comment]
Done

**Comment by brcinho** [comment]
The rest has been fixed, but maybe this is also related to XF 4.5 change, it worked in XF 4.3

The following:

                var view = new MaterialRadioButtonGroup(choices);
                var result = await MaterialDialog.Instance.ShowCustomContentAsync(view, description, title);

But currently in XF 4.5 the radiobuttons (and the checkboxes in checkboxgroup) are hidden, while their text is visible.

**Comment by mtsrdr** [comment]
> But currently in XF 4.5 the radiobuttons (and the checkboxes in checkboxgroup) are hidden, while their text is visible.

I also noticed this in version 1.6.1. It seems that the issue #186 is still happening and the changes made to fix it are just trying to force VS to include iOS Assets when building, but have not effectively fixed it.

@martijn00 could you please clean, rebuild and release a new version of XF.Material?

**Comment by martijn00** [comment]
@mtsrdr Done, published 1.6.2 now.

**Comment by mtsrdr** [comment]
> @mtsrdr Done, published 1.6.2 now.

Unfortunately, it didn't work.

```
2020-04-04 15:35:33.391851-0300 BolabookV2.iOS[5040:177050] Image loading failed: xf_radio_button_selected
System.IO.FileNotFoundException: xf_radio_button_selected
  at FFImageLoading.DataResolvers.BundleDataResolver.Resolve (System.String identifier, FFImageLoading.Work.TaskParameter parameters, System.Threading.CancellationToken token) [0x001ee] in C:\projects\ffimageloading\source\FFImageLoading.Shared.IosMac\DataResolvers\BundleDataResolver.cs:47 
  at FFImageLoading.DataResolvers.WrappedDataResolver.Resolve (System.String identifier, FFImageLoading.Work.TaskParameter parameters, System.Threading.CancellationToken token) [0x0004e] in C:\projects\ffimageloading\source\FFImageLoading.Common\DataResolvers\WrappedDataResolver.cs:21 
  at FFImageLoading.Work.ImageLoaderTask`3[TDecoderContainer,TImageContainer,TImageView].RunAsync () [0x00300] in C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:618
```

**Comment by mtsrdr** [comment]
@martijn00 , versions 1.6.1 and 1.6.2 were built in VS for Windows?

I have done some testing and I think VS for Windows is ignoring the assets of iOS when building the package.
